#############################################################################
# Makefile for building: SerialTest
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  SerialTest.pro
# Template: app
# Command: /opt/qt-everywhere-opensource-src-5.5.1/__install/bin/qmake -o Makefile SerialTest.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=armv7-a -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=armv7-a -O2 -march=armv7-a -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore -I. -I. -I/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /opt/qt-everywhere-opensource-src-5.5.1/__install/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SerialTest1.0.0
DISTDIR = /mnt/hgfs/vmwareShareFolder/serial_test/SerialTest/.tmp/SerialTest1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-everywhere-opensource-src-5.5.1/__install/lib
LIBS          = $(SUBLIBS) -L/opt/qt-everywhere-opensource-src-5.5.1/__install/lib -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Core -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SerialDialog.cpp \
		DataProcessThread.cpp moc_SerialDialog.cpp \
		moc_DataProcessThread.cpp
OBJECTS       = main.o \
		SerialDialog.o \
		DataProcessThread.o \
		moc_SerialDialog.o \
		moc_DataProcessThread.o
DIST          = /opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/spec_pre.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/unix.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/linux.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/sanitize.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/gcc-base.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/g++-base.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/g++-unix.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/qconfig.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_core.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_help.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_network.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_script.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt_functions.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt_config.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/spec_post.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/exclusive_builds.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/default_pre.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/resolve_config.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/default_post.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/warn_on.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/resources.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/moc.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/uic.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/unix/thread.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/testcase_targets.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/exceptions.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/yacc.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/lex.prf \
		SerialTest.pro SerialDialog.h \
		DataProcessThread.h main.cpp \
		SerialDialog.cpp \
		DataProcessThread.cpp
QMAKE_TARGET  = SerialTest
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SerialTest


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_SerialDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SerialTest.pro /opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/linux-arm-gnueabi-g++/qmake.conf /opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/spec_pre.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/unix.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/linux.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/sanitize.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/gcc-base.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/g++-base.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/g++-unix.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/qconfig.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_core.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_help.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_network.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_script.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt_functions.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt_config.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/spec_post.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/exclusive_builds.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/default_pre.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/resolve_config.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/default_post.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/warn_on.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/resources.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/moc.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/uic.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/unix/thread.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/testcase_targets.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/exceptions.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/yacc.prf \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/lex.prf \
		SerialTest.pro \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5Widgets.prl \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5Gui.prl \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5SerialPort.prl \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5Core.prl
	$(QMAKE) -o Makefile SerialTest.pro
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/spec_pre.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/unix.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/linux.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/sanitize.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/gcc-base.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/gcc-base-unix.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/g++-base.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/common/g++-unix.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/qconfig.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_core.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_gui.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_help.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_network.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qml.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_script.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sql.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_svg.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xml.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt_functions.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt_config.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/spec_post.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/exclusive_builds.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/default_pre.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/resolve_config.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/default_post.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/warn_on.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/qt.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/resources.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/moc.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/uic.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/unix/thread.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/testcase_targets.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/exceptions.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/yacc.prf:
/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/features/lex.prf:
SerialTest.pro:
/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5Widgets.prl:
/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5Gui.prl:
/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5SerialPort.prl:
/opt/qt-everywhere-opensource-src-5.5.1/__install/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SerialTest.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents SerialDialog.h DataProcessThread.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp SerialDialog.cpp DataProcessThread.cpp $(DISTDIR)/
	$(COPY_FILE) --parents SerialDialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_SerialDialog.cpp moc_DataProcessThread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SerialDialog.cpp moc_DataProcessThread.cpp
moc_SerialDialog.cpp: /opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/QDialog \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qdialog.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qwidget.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qwindowdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobal.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qconfig.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfeatures.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsystemdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qprocessordetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcompilerdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypeinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypetraits.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsysinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlogging.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qflags.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbasicatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qgenericatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_cxx11.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_gcc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_msvc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv7.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv6.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv5.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_ia64.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_mips.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_x86.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_unix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobalstatic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmutex.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnumeric.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnamespace.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qwindowdefs_win.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstring.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qchar.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrefcount.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qarraydata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringbuilder.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qalgorithms.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiterator.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearraylist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qregexp.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringmatcher.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcoreevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qscopedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmetatype.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvarlengtharray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontainerfwd.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qisenum.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmargins.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpaintdevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrect.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsize.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qpoint.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpalette.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qcolor.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qrgb.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qbrush.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qpair.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvector.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qmatrix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpolygon.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qregion.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qdatastream.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiodevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qline.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtransform.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpainterpath.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qimage.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpixelformat.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpixmap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsharedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qshareddata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qhash.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfont.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfontmetrics.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfontinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qsizepolicy.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qcursor.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qkeysequence.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvariant.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qdebug.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtextstream.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlocale.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qset.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontiguouscache.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qurl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qurlquery.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfile.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfiledevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qvector2d.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtouchdevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/QSerialPort \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialport.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialportglobal.h \
		DataProcessThread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QThread \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qthread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QMutex \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QWaitCondition \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qwaitcondition.h \
		SerialDialog.h
	/opt/qt-everywhere-opensource-src-5.5.1/__install/bin/moc $(DEFINES) -I/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/linux-arm-gnueabi-g++ -I/mnt/hgfs/vmwareShareFolder/serial_test/SerialTest -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.3.1 -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.3.1/arm-linux-gnueabihf -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.3.1/backward -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.3.1/include -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.3.1/include-fixed -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/include SerialDialog.h -o moc_SerialDialog.cpp

moc_DataProcessThread.cpp: /opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QThread \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qthread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnamespace.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobal.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qconfig.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfeatures.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsystemdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qprocessordetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcompilerdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypeinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypetraits.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsysinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlogging.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qflags.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbasicatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qgenericatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_cxx11.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_gcc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_msvc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv7.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv6.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv5.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_ia64.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_mips.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_x86.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_unix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobalstatic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmutex.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnumeric.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstring.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qchar.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrefcount.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qarraydata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringbuilder.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qalgorithms.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiterator.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearraylist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qregexp.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringmatcher.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcoreevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qscopedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmetatype.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvarlengtharray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontainerfwd.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qisenum.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QMutex \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QWaitCondition \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qwaitcondition.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/QSerialPort \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialport.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiodevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialportglobal.h \
		DataProcessThread.h
	/opt/qt-everywhere-opensource-src-5.5.1/__install/bin/moc $(DEFINES) -I/opt/qt-everywhere-opensource-src-5.5.1/__install/mkspecs/linux-arm-gnueabi-g++ -I/mnt/hgfs/vmwareShareFolder/serial_test/SerialTest -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort -I/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.3.1 -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.3.1/arm-linux-gnueabihf -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/5.3.1/backward -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.3.1/include -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/5.3.1/include-fixed -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/opt/EmbedSky/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/include DataProcessThread.h -o moc_DataProcessThread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_SerialDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_SerialDialog.h
ui_SerialDialog.h: SerialDialog.ui
	/opt/qt-everywhere-opensource-src-5.5.1/__install/bin/uic SerialDialog.ui -o ui_SerialDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp SerialDialog.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/QDialog \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qdialog.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qwidget.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qwindowdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobal.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qconfig.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfeatures.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsystemdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qprocessordetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcompilerdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypeinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypetraits.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsysinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlogging.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qflags.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbasicatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qgenericatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_cxx11.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_gcc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_msvc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv7.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv6.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv5.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_ia64.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_mips.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_x86.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_unix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobalstatic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmutex.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnumeric.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnamespace.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qwindowdefs_win.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstring.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qchar.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrefcount.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qarraydata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringbuilder.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qalgorithms.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiterator.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearraylist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qregexp.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringmatcher.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcoreevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qscopedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmetatype.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvarlengtharray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontainerfwd.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qisenum.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmargins.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpaintdevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrect.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsize.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qpoint.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpalette.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qcolor.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qrgb.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qbrush.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qpair.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvector.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qmatrix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpolygon.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qregion.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qdatastream.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiodevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qline.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtransform.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpainterpath.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qimage.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpixelformat.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpixmap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsharedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qshareddata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qhash.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfont.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfontmetrics.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfontinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qsizepolicy.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qcursor.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qkeysequence.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvariant.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qdebug.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtextstream.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlocale.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qset.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontiguouscache.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qurl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qurlquery.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfile.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfiledevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qvector2d.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtouchdevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/QSerialPort \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialport.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialportglobal.h \
		DataProcessThread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QThread \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qthread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QMutex \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QWaitCondition \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qwaitcondition.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/QApplication \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qapplication.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcoreapplication.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qeventloop.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qdesktopwidget.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qguiapplication.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

SerialDialog.o: SerialDialog.cpp SerialDialog.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/QDialog \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qdialog.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qwidget.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qwindowdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobal.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qconfig.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfeatures.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsystemdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qprocessordetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcompilerdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypeinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypetraits.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsysinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlogging.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qflags.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbasicatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qgenericatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_cxx11.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_gcc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_msvc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv7.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv6.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv5.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_ia64.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_mips.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_x86.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_unix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobalstatic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmutex.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnumeric.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnamespace.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qwindowdefs_win.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstring.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qchar.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrefcount.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qarraydata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringbuilder.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qalgorithms.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiterator.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearraylist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qregexp.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringmatcher.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcoreevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qscopedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmetatype.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvarlengtharray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontainerfwd.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qisenum.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmargins.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpaintdevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrect.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsize.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qpoint.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpalette.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qcolor.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qrgb.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qbrush.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qpair.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvector.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qmatrix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpolygon.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qregion.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qdatastream.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiodevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qline.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtransform.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpainterpath.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qimage.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpixelformat.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpixmap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsharedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qshareddata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qhash.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfont.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfontmetrics.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qfontinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qsizepolicy.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qcursor.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qkeysequence.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvariant.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qdebug.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtextstream.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlocale.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qset.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontiguouscache.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qurl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qurlquery.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfile.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfiledevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qvector2d.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtouchdevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/QSerialPort \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialport.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialportglobal.h \
		DataProcessThread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QThread \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qthread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QMutex \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QWaitCondition \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qwaitcondition.h \
		ui_SerialDialog.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/QSerialPortInfo \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialportinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/QIntValidator \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qvalidator.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qregularexpression.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/QLineEdit \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qlineedit.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtWidgets/qframe.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtextcursor.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtextformat.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qpen.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtGui/qtextoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SerialDialog.o SerialDialog.cpp

DataProcessThread.o: DataProcessThread.cpp DataProcessThread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QThread \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qthread.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnamespace.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobal.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qconfig.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qfeatures.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsystemdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qprocessordetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcompilerdetection.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypeinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qtypetraits.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qsysinfo.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlogging.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qflags.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbasicatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qgenericatomic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_cxx11.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_gcc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_msvc.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv7.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv6.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_armv5.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_ia64.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_mips.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_x86.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qatomic_unix.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qglobalstatic.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmutex.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qnumeric.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstring.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qchar.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qrefcount.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qarraydata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringbuilder.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qalgorithms.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiterator.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qbytearraylist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringlist.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qregexp.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qstringmatcher.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcoreevent.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qscopedpointer.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qmetatype.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qvarlengtharray.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qcontainerfwd.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qisenum.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qobject_impl.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QMutex \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QWaitCondition \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qwaitcondition.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/QSerialPort \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialport.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qiodevice.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtSerialPort/qserialportglobal.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/QTime \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qdatetime.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qshareddata.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qhash.h \
		/opt/qt-everywhere-opensource-src-5.5.1/__install/include/QtCore/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataProcessThread.o DataProcessThread.cpp

moc_SerialDialog.o: moc_SerialDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SerialDialog.o moc_SerialDialog.cpp

moc_DataProcessThread.o: moc_DataProcessThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DataProcessThread.o moc_DataProcessThread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

